import { useEffect, useReducer, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { Activity, ArrowLeft, ArrowUpLeft, Bell, BookOpen, Box, Check, CheckCheck,
  ChevronLeft, ChevronRight, CircleHelp, Clock3, Cpu, Database, ExternalLink, Filter, Globe2, HardDrive,
  LayoutGrid, List, LoaderCircle, LockKeyhole, Menu, MoreHorizontal, Network, Pause, Play, Plus, Power,
  Radio, RotateCcw, Search, Server, Settings2, ShieldCheck, Smartphone, Terminal, Users, X, Zap } from 'lucide-react';
import { parseResourceReport, type ResourceReport } from './resources';
import { fa, initialState, maskPhone, reducer, reserved, statusText, type Device, type DeviceStatus } from './domain';

type Page = 'devices' | 'sessions' | 'proxies' | 'backups' | 'events' | 'architecture' | 'settings';
type ManagedProxy = { id: string; label: string; type: 'SOCKS5' | 'HTTP'; region: string;
  endpoint: string; expectedIp: string; assigned: string | null; healthy: boolean };
const pages: { id: Page; title: string; icon: typeof Smartphone }[] = [
  { id: 'devices', title: 'دستگاه‌ها', icon: LayoutGrid }, { id: 'sessions', title: 'جلسات و صف', icon: Radio },
  { id: 'proxies', title: 'شبکه و پراکسی', icon: Network }, { id: 'backups', title: 'پشتیبان‌ها', icon: Database },
  { id: 'events', title: 'رویدادها', icon: Activity }, { id: 'architecture', title: 'معماری سیستم', icon: Box },
  { id: 'settings', title: 'تنظیمات فارم', icon: Settings2 },
];
const time = (stamp: number) => new Date(stamp).toLocaleTimeString('fa-IR', { hour: '2-digit', minute: '2-digit' });
function Status({ status }: { status: DeviceStatus }) { return <span className={`status ${status}`}><i />{statusText[status]}</span>; }
function IconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick: () => void }) {
  return <button className="icon-button" aria-label={label} title={label} onClick={onClick}>{children}</button>;
}
function Modal({ children, title, onClose, wide = false }: { children: ReactNode; title: string; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current!; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog className={wide ? 'modal wide' : 'modal'} ref={ref} aria-label={title} onCancel={onClose}
    onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="modal-head"><h2>{title}</h2>
    <IconButton label="بستن" onClick={onClose}><X size={20} /></IconButton></div>{children}</dialog>;
}

export default function App() {
  const [hostReport] = useState<ResourceReport>(() => parseResourceReport({ schema_version: 2,
    collected_at: Date.now() / 1000, cpu_cores: 72, ram_gib: 96, available_ram_gib: 80,
    disk_free_gib: 640, capacity: 10, active_capacity: 10, catalog_capacity: 50, per_device_disk_gib: 12 }));
  const [state, dispatch] = useReducer(reducer, undefined, initialState);
  const [page, setPage] = useState<Page>(() => (pages.find(p => p.id === location.hash.slice(1))?.id ?? 'devices'));
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [view, setView] = useState<'grid' | 'list'>('grid');
  const [pageIndex, setPageIndex] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [detailTab, setDetailTab] = useState('overview');
  const [addOpen, setAddOpen] = useState(false);
  const [help, setHelp] = useState(false);
  const [confirm, setConfirm] = useState<Device | null>(null);
  const [navOpen, setNavOpen] = useState(false);
  const [toast, setToast] = useState('');
  const [jobLabel, setJobLabel] = useState('');
  const [jobPhone, setJobPhone] = useState('');
  const [formError, setFormError] = useState('');
  const [proxyOpen, setProxyOpen] = useState(false);
  const [proxyLabel, setProxyLabel] = useState('');
  const [proxyRegion, setProxyRegion] = useState('آلمان');
  const [proxyType, setProxyType] = useState<'SOCKS5' | 'HTTP'>('SOCKS5');
  const [managedProxies, setManagedProxies] = useState<ManagedProxy[]>([]);
  const [compact, setCompact] = useState(false);
  const [backupInfo, setBackupInfo] = useState<string | null>(null);
  const running = state.devices.filter(d => d.status === 'running');
  const activeCount = reserved(state.devices);
  const queued = state.devices.filter(d => d.status === 'queued').sort((a, b) => (a.queueOrder ?? 0) - (b.queueOrder ?? 0));
  const errors = state.devices.filter(d => !d.proxyHealthy);
  const chosen = state.devices.find(d => d.id === selected);
  const title = pages.find(p => p.id === page)!.title;
  useEffect(() => { dispatch({ type: 'capacity', capacity: hostReport.active_capacity }); }, [hostReport.active_capacity]);
  useEffect(() => { const timer = setInterval(() => dispatch({ type: 'tick' }), 2800); return () => clearInterval(timer); }, []);
  useEffect(() => { if (state.message) setToast(state.message); }, [state.message, state.events.length]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { const handler = () => { setPage(pages.find(p => p.id === location.hash.slice(1))?.id ?? 'devices'); setQuery(''); setFilter('all'); setPageIndex(0); };
    window.addEventListener('hashchange', handler); return () => window.removeEventListener('hashchange', handler); }, []);
  function navigate(next: Page) { setPage(next); location.hash = next; setQuery(''); setFilter('all'); setPageIndex(0); setNavOpen(false); window.scrollTo({top: 0}); }
  function openDevice(d: Device, tab = 'overview') { setSelected(d.id); setDetailTab(tab); }
  const normalized = query.trim().toLowerCase().replace(/[۰-۹]/g, d => String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));
  const matches = (d: Device) => `${d.id} ${d.label} ${d.phone} ${d.region}`.toLowerCase().includes(normalized);
  const filtered = state.devices.filter(d => matches(d) && (filter === 'all' || (filter === 'running' ? ['running', 'booting'].includes(d.status) : d.status === filter)));
  const visible = filtered.slice(pageIndex * 12, (pageIndex + 1) * 12);
  const pageCount = Math.max(1, Math.ceil(filtered.length / 12));
  useEffect(() => { setPageIndex(current => Math.min(current, pageCount - 1)); }, [pageCount]);
  function addDevice(e: FormEvent) {
    e.preventDefault();
    if (!/^\+\d{10,15}$/.test(jobPhone)) return setFormError('شمارهٔ آزمایشی را با + و کد کشور وارد کنید.');
    if (state.devices.some(d => d.phone === jobPhone)) return setFormError('این شماره قبلاً به دستگاه دیگری اختصاص یافته است.');
    dispatch({ type: 'add', label: jobLabel, phone: jobPhone }); setAddOpen(false); setJobLabel(''); setJobPhone('');
    setFilter('all'); setQuery(''); setPageIndex(Math.floor(state.devices.length / 12));
  }
  function addProxy(e: FormEvent) {
    e.preventDefault();
    const n = managedProxies.length + 1;
    setManagedProxies(items => [...items, { id: `proxy-${String(n).padStart(3, '0')}`,
      label: proxyLabel.trim(), type: proxyType, region: proxyRegion,
      endpoint: 'ثبت امن در backend', expectedIp: 'تأیید پس از تست', assigned: null, healthy: false }]);
    setProxyOpen(false); setProxyLabel(''); setToast('اتصال پراکسی نمونه به رجیستری افزوده شد');
  }
  const quickAction = (d: Device) => d.status === 'running' ? openDevice(d, 'screen') : d.status === 'queued' ? dispatch({ type: 'cancel', id: d.id }) : dispatch({ type: 'start', id: d.id });
  const actionLabel = (d: Device) => d.status === 'running' ? 'کنترل دستگاه' : d.status === 'queued' ? 'لغو درخواست' : d.status === 'error' ? 'بررسی اتصال' : 'روشن کردن';

  return <div className={`app ${compact ? 'compact' : ''}`}>
    {navOpen && <button className="nav-overlay" aria-label="بستن منو" onClick={() => setNavOpen(false)} />}
    <aside className={`sidebar ${navOpen ? 'open' : ''}`}>
      <a className="brand" href="#devices" onClick={() => navigate('devices')}><div className="brand-mark"><i /><i /><i /><i /></div><span>Android Farm<small>کنسول عملیات</small></span></a>
      <div className="workspace"><span className="workspace-icon"><Server size={19} /></span><div>فارم اصلی<small>سرور هنوز متصل نیست</small></div><span className="live-dot" /></div>
      <p className="nav-label">فضای کاری</p>
      <nav>{pages.slice(0, 5).map(({ id, title, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => navigate(id)}><Icon size={20} /><span>{title}</span>
        {id === 'devices' && <b>{fa(state.devices.length)}</b>}{id === 'sessions' && queued.length > 0 && <b>{fa(queued.length)}</b>}{id === 'proxies' && errors.length > 0 && <span className="nav-dot" />}</button>)}</nav>
      <p className="nav-label second">مدیریت</p><nav>{pages.slice(5).map(({ id, title, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => navigate(id)}><Icon size={20} /><span>{title}</span></button>)}</nav>
      <div className="sidebar-bottom"><div className="host-card"><div><span className="live-dot" /><b>میزبان آزمایشی</b><span className="host-tag">DEMO</span></div><p>{`${fa(hostReport.cpu_cores)} هسته · ${fa(hostReport.ram_gib)} گیگابایت`}</p><div className="host-meter"><i style={{ width: `${Math.min(100, state.capacity ? activeCount / state.capacity * 100 : 0)}%` }} /></div><small>نمونهٔ تشخیص خودکار منابع</small></div>
      <button className="help-button" onClick={() => setHelp(true)}><CircleHelp size={19} /> راهنمای عملیات <ArrowUpLeft size={16} /></button>
      <div className="profile"><div className="avatar">م</div><div>مدیر عملیات<small>نقش نمایشی: مدیر</small></div><span className="profile-dot" /></div></div>
    </aside>

    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="منو" onClick={() => setNavOpen(true)}><Menu size={22} /></button><span>فضای کاری</span><ChevronLeft size={15} /><strong>{title}</strong></div>
      <div className="topbar-left"><span className="demo-pill"><span />نسخهٔ تعاملی طراحی</span><span className="top-divider" /><IconButton label="مشاهده رویدادها" onClick={() => navigate('events')}><Bell size={19} />{errors.length > 0 && <i className="notification-dot" />}</IconButton><button className="mini-avatar" aria-label="تنظیمات حساب و دسترسی" onClick={() => navigate('settings')}>م</button></div></header>

      <main>
        <div className="page-heading"><div><div className="eyebrow">ANDROID FARM <span>/</span> OPERATIONS</div><h1>{page === 'devices' ? 'همهٔ دستگاه‌ها، یک فضای کار.' : title}</h1><p>{({ devices: 'دستگاه‌ها را آماده کنید، جلسه را شروع کنید و کنترل را در دست بگیرید.', sessions: 'جایگاه‌های فعال و درخواست‌های منتظر را مدیریت کنید.', proxies: 'برای هر دستگاه، یک مسیر خروجی مستقل و پایدار.', backups: 'داده‌های هر دستگاه، مستقل و قابل بازیابی.', events: 'ردپای روشنِ هر اتفاق در فارم.', architecture: 'از فرمان اپراتور تا دستگاه؛ با مرزهای مشخص.', settings: 'سیاست‌های ظرفیت، نگهداری و دسترسی تیم.' })[page]}</p></div>
          {page === 'devices' ? <button className="primary" onClick={() => { setFormError(''); setAddOpen(true); }}><Plus size={18} />افزودن دستگاه</button> : page === 'proxies' ? <button className="primary" onClick={() => setProxyOpen(true)}><Plus size={18} />افزودن پراکسی</button> : <span className="section-chip"><span className="live-dot" />محیط نمونه</span>}</div>

        {page === 'devices' && <>
          <section className="panel setup-panel"><div><span className="eyebrow">SMART HOST DISCOVERY</span><h2>ظرفیت میزبان خودکار محاسبه شد</h2><p>نصب‌کننده CPU، RAM، cgroup، دیسک داده و inode را می‌سنجد؛ اپراتور نیازی به تنظیم Coolify یا واردکردن گزارش ندارد.</p>
          <p>همزمان روشن: <b>{fa(hostReport.active_capacity)} دستگاه</b> · ظرفیت افزودهٔ داده: <b>{fa(hostReport.catalog_capacity ?? 0)} دستگاه</b> · حافظهٔ آزاد: {fa(hostReport.available_ram_gib)} GB · دیسک آزاد: {fa(hostReport.disk_free_gib)} GB</p></div><span className="status running"><i />تشخیص خودکار</span></section>
          <section className="capacity-panel" aria-label="ظرفیت جلسات"><div className="capacity-title"><div className="capacity-icon"><Zap size={23} /></div><div><h2>ظرفیت روشن، تحت کنترل</h2><p>سقف ثابت وجود ندارد؛ مقدار امن با منابع همین میزبان و فشار لحظه‌ای تعیین می‌شود.</p></div></div>
            <div className="slots-wrap"><div className="slots-label"><b>{fa(activeCount)} <span>از {fa(state.capacity)} جایگاه فعال</span></b><span>{fa(Math.max(0, state.capacity - activeCount))} جایگاه آزاد</span></div><div className="slots" aria-label={`${activeCount} از ${state.capacity}`}><div className={activeCount ? 'filled' : ''} style={{ width: `${Math.min(100, state.capacity ? activeCount / state.capacity * 100 : 0)}%` }}><Smartphone size={18} /></div></div></div>
            <button className="capacity-link" onClick={() => navigate('sessions')}>مدیریت جلسات<ArrowLeft size={17} /></button></section>

          <section className="stats-grid" aria-label="خلاصه فارم"><Stat icon={<Smartphone />} label="کل دستگاه‌ها" value={fa(state.devices.length)} note="دادهٔ پایدار و مستقل" spark="neutral" />
            <Stat icon={<Radio />} label="آماده به کار" value={fa(running.length)} note="آمادهٔ کنترل از مرورگر" spark="green" />
            <Stat icon={<ShieldCheck />} label="پراکسی‌های سالم" value={fa(state.devices.length - errors.length)} suffix={`/ ${fa(state.devices.length)}`} note="اتصال نمونهٔ اختصاصی" spark="teal" />
            <Stat icon={<Activity />} label="نیاز به بررسی" value={fa(errors.length)} note={errors.length ? 'اتصال پراکسی بررسی شود' : 'موردی برای بررسی نیست'} spark="orange" /></section>

          <section className="fleet-section"><div className="section-header"><div className="section-title"><h2>ناوگان دستگاه‌ها</h2><span>{fa(state.devices.length)} دستگاه</span></div><div className="view-toggle" aria-label="شیوه نمایش"><button className={view === 'grid' ? 'active' : ''} aria-label="نمای کارت" aria-pressed={view === 'grid'} onClick={() => setView('grid')}><LayoutGrid size={17} /></button><button className={view === 'list' ? 'active' : ''} aria-label="نمای جدول" aria-pressed={view === 'list'} onClick={() => setView('list')}><List size={18} /></button></div></div>
            <div className="toolbar"><div className="filter-tabs">{[['all', 'همه'], ['running', 'روشن'], ['off', 'خاموش'], ['error', 'نیاز به بررسی'], ['queued', 'در صف']].map(([id, text]) => <button key={id} className={filter === id ? 'selected' : ''} onClick={() => { setFilter(id); setPageIndex(0); }}>{text}{id === 'all' && <span>{fa(state.devices.length)}</span>}{id === 'running' && <span>{fa(running.length)}</span>}</button>)}</div><SearchField query={query} onChange={v => { setQuery(v); setPageIndex(0); }} /></div>
            {visible.length === 0 ? <Empty title={state.devices.length ? "دستگاهی پیدا نشد" : "دستگاه اول شما: num01"} text={state.devices.length ? "جست‌وجو یا فیلتر را تغییر دهید." : "هیچ دستگاهی از پیش ساخته نشده است. با افزودن دستگاه، پیش‌نمایش جریان کار را شروع کنید."} action={() => { setQuery(''); setFilter('all'); }} /> : view === 'grid' ? <div className="device-grid">{visible.map(d => <article className={`device-card ${d.status === 'running' ? 'is-running' : ''}`} key={d.id}>
              <div className="device-top"><div className={`device-symbol ${d.status}`}><Smartphone size={23} />{d.status === 'running' && <i />}</div><div className="device-name"><button onClick={() => openDevice(d)}><b dir="ltr">{d.id}</b><ArrowUpLeft size={13} /></button><span>{d.label}</span></div><IconButton label={`جزئیات ${d.id}`} onClick={() => openDevice(d)}><MoreHorizontal size={20} /></IconButton></div>
              <div className="device-phone"><span>شمارهٔ اختصاصی</span><b dir="ltr">{maskPhone(d.phone)}</b></div>
              <div className="device-network"><Globe2 size={15} /><span>{d.region}</span><span className="network-divider">/</span><span dir="ltr">Sticky IP</span><span className={d.proxyHealthy ? 'network-ok' : 'network-error'}>{d.proxyHealthy ? <><i />{d.latency} ms</> : 'قطع اتصال'}</span></div>
              <div className="device-footer"><Status status={d.status} /><button className={`device-action ${d.status === 'running' ? 'running-action' : ''}`} disabled={['booting', 'stopping', 'backup'].includes(d.status)} onClick={() => d.status === 'error' ? openDevice(d) : quickAction(d)}>{['booting', 'stopping', 'backup'].includes(d.status) ? <LoaderCircle size={15} className="spin" /> : d.status === 'running' ? <ArrowUpLeft size={15} /> : d.status === 'queued' ? <X size={14} /> : <Power size={14} />}{actionLabel(d)}</button></div>
            </article>)}</div> : <div className="table-wrap"><table><thead><tr><th>دستگاه</th><th>شماره</th><th>وضعیت</th><th>پراکسی</th><th>عملیات</th></tr></thead><tbody>{visible.map(d => <tr key={d.id}><td><button className="text-button mono" onClick={() => openDevice(d)}>{d.id}</button><small>{d.label}</small></td><td dir="ltr">{maskPhone(d.phone)}</td><td><Status status={d.status} /></td><td>{d.region}</td><td><button className="secondary small" onClick={() => openDevice(d)}>جزئیات <ArrowUpLeft size={14} /></button></td></tr>)}</tbody></table></div>}
            <div className="pagination"><span>نمایش {fa(filtered.length ? pageIndex * 12 + 1 : 0)} تا {fa(Math.min((pageIndex + 1) * 12, filtered.length))} از {fa(filtered.length)} دستگاه</span><div><button aria-label="صفحه قبل" disabled={pageIndex === 0} onClick={() => setPageIndex(p => p - 1)}><ChevronRight size={16} /></button>{Array.from({ length: pageCount }, (_, i) => <button key={i} className={i === pageIndex ? 'current' : ''} aria-label={`صفحه ${fa(i + 1)}`} aria-current={i === pageIndex ? 'page' : undefined} onClick={() => setPageIndex(i)}>{fa(i + 1)}</button>)}<button aria-label="صفحه بعد" disabled={pageIndex >= pageCount - 1} onClick={() => setPageIndex(p => p + 1)}><ChevronLeft size={16} /></button></div></div>
          </section>
          <div className="bottom-note"><LockKeyhole size={14} />اطلاعات این محیط نمونه است؛ هیچ فرمانی به سرور واقعی ارسال نمی‌شود.<button onClick={() => navigate('architecture')}>مشاهدهٔ معماری <ArrowLeft size={14} /></button></div>
        </>}

        {page === 'sessions' && <><div className="sessions-banner"><div><Radio size={30} /><h2>{fa(activeCount)} جایگاه در استفاده</h2><p>رزرو ظرفیت از آغاز راه‌اندازی تا تأیید خاموش‌شدن حفظ می‌شود.</p></div><div className="capacity-number">{fa(activeCount)}<span>/ {fa(state.capacity)}</span></div></div><div className="two-columns"><section className="panel"><div className="section-header"><h2>جلسات فعال</h2><span className="section-chip">{fa(activeCount)} دستگاه</span></div>{state.devices.filter(d => ['running', 'booting', 'stopping'].includes(d.status)).map(d => <div className="session-row" key={d.id}><div className="round-icon"><Smartphone size={20} /></div><div><b dir="ltr">{d.id}</b><p>{d.label}</p></div><Status status={d.status} /><button className="secondary small" disabled={d.status === 'stopping'} onClick={() => setConfirm(d)}><Pause size={14} />پایان جلسه</button></div>)}</section><section className="panel"><div className="section-header"><h2>صف انتظار</h2><span className="section-chip">{fa(queued.length)} درخواست</span></div>{queued.length ? queued.map((d, i) => <div className="session-row" key={d.id}><span className="queue-index">{fa(i + 1)}</span><div><b dir="ltr">{d.id}</b><p>منتظر آزادشدن جایگاه</p></div><button className="text-button" onClick={() => dispatch({ type: 'cancel', id: d.id })}>لغو</button></div>) : <Empty title="صف خالی است" text="وقتی ظرفیت تکمیل شود، درخواست جدید اینجا منتظر می‌ماند." />}</section></div></>}

        {page === 'proxies' && <><div className="notice"><ShieldCheck size={22} /><div><strong>رجیستری داخلی پراکسی</strong><p>credential به‌صورت write-only ثبت می‌شود؛ IP خروجی پیش از تخصیص تست می‌شود و هر اتصال فقط به یک دستگاه اختصاص می‌یابد.</p></div></div><div className="panel"><div className="section-header"><h2>اتصال‌های مدیریت‌شده</h2><span className="section-chip">{fa(managedProxies.length)} اتصال</span></div>{managedProxies.length ? <div className="table-wrap"><table><thead><tr><th>شناسه</th><th>عنوان</th><th>موقعیت</th><th>نوع</th><th>تخصیص</th><th>سلامت</th></tr></thead><tbody>{managedProxies.map(proxy => <tr key={proxy.id}><td className="mono">{proxy.id}</td><td>{proxy.label}</td><td><span className="inline"><Globe2 size={16} />{proxy.region}</span></td><td><span className="tag">{proxy.type} · Sticky</span></td><td>{proxy.assigned ?? 'آزاد'}</td><td><span className={`status ${proxy.healthy ? 'running' : 'off'}`}><i />{proxy.healthy ? 'تأییدشده' : 'نیازمند تست'}</span></td></tr>)}</tbody></table></div> : <Empty title="هنوز پراکسی ثبت نشده" text="یک اتصال اختصاصی HTTP یا SOCKS5 اضافه کنید؛ credential در رابط دوباره نمایش داده نمی‌شود." />}</div></>}

        {page === 'backups' && <><div className="notice"><Database size={22} /><div><strong>پشتیبان سازگار، پس از پایان جلسه</strong><p>دستگاه باید خاموش باشد. بکاپ نمونه از بخش جزئیات هر دستگاه قابل ثبت است.</p></div><button className="secondary" onClick={() => navigate('devices')}>انتخاب دستگاه<ArrowLeft size={16} /></button></div><section className="panel"><div className="section-header"><h2>تاریخچهٔ پشتیبان‌ها</h2><span className="section-chip">{fa(state.backups.length)} نسخهٔ نمونه</span></div><div className="table-wrap"><table><thead><tr><th>دستگاه</th><th>زمان ثبت</th><th>اندازهٔ نمونه</th><th>وضعیت</th><th>جزئیات</th></tr></thead><tbody>{state.backups.map(b => <tr key={b.id}><td><b className="mono">{b.device}</b></td><td>{time(b.at)}</td><td dir="ltr">{b.size}</td><td><span className="status running"><CheckCheck size={14} />ثبت‌شده در نمونه</span></td><td><button className="secondary small" onClick={() => setBackupInfo(b.device)}>مشاهده <ArrowUpLeft size={14} /></button></td></tr>)}</tbody></table></div></section></>}

        {page === 'events' && <section className="panel"><div className="section-header"><h2>رویدادهای این جلسهٔ نمایشی</h2><SearchField query={query} onChange={setQuery} /></div><div className="events-list">{state.events.filter(e => `${e.device} ${e.text}`.includes(query)).map(e => <div className="event" key={e.id}><span className={`event-icon ${e.kind}`}>{e.kind === 'success' ? <Check size={17} /> : e.kind === 'warning' ? <Activity size={17} /> : <Clock3 size={17} />}</span><div><strong>{e.text}</strong><p><b className="mono">{e.device}</b><span>·</span>مدیر عملیات</p></div><time>{time(e.at)}</time></div>)}</div></section>}

        {page === 'architecture' && <><section className="architecture-hero"><div><span className="eyebrow">CONTROL PLANE / DEVICE PLANE</span><h2>یک پلتفرم واحد.<br />داده و شبکهٔ اختصاصی برای هر دستگاه.</h2><p>نصب‌کننده زیرساخت را آماده می‌کند؛ کنترل‌پلین ظرفیت و صف را مدیریت می‌کند؛ عامل میزبان چرخهٔ امن هر دستگاه را اجرا می‌کند.</p></div><div className="arch-emblem"><Box size={65} strokeWidth={1} /><span>مقیاس‌پذیر بر اساس منابع</span></div></section><div className="architecture-flow">{[{ icon: Users, title: 'کنسول نمایشی', sub: 'پیش‌نمایش دستگاه، پراکسی، صف و پشتیبان' }, { icon: ShieldCheck, title: 'درگاه امن', sub: 'TLS و احراز هویت مشترک مسیرمحور' }, { icon: Server, title: 'کنترل‌پلین میزبان', sub: 'ظرفیت پویا، صف Redis و journal' }, { icon: Terminal, title: 'عامل میزبان', sub: 'فرمان محدود و health check' }, { icon: Smartphone, title: 'Device Pod', sub: 'Proxy + Redroid + Screen + Data' }].map((item, i) => <div className="flow-node" key={item.title}><span>{String(i + 1).padStart(2, '0')}</span><item.icon size={28} /><h3>{item.title}</h3><p>{item.sub}</p></div>)}</div><div className="two-columns"><section className="panel architecture-panel"><h2><CheckCheck size={20} />قابلیت‌های عملیاتی</h2><ul><li>تشخیص خودکار CPU، RAM، cgroup، فضای داده و inode.</li><li>رجیستری داخلی پراکسی، تست IP و تخصیص یک‌به‌یک.</li><li>صف روشن‌سازی، توقف امن و حفظ همیشگی دادهٔ هر دستگاه.</li><li>کنترل صفحه از مرورگر و ADB فقط روی loopback.</li><li>بکاپ offline، checksum، hold ایمنی، manifest و journal.</li></ul></section><section className="panel architecture-panel"><h2><LockKeyhole size={20} />مرزهای امنیتی و وضعیت</h2><ul><li>Docker Socket در اختیار پنل وب نیست.</li><li>credential پراکسی در UI، ENV و log نمایش داده نمی‌شود.</li><li>خروجی مستقیم با kill-switch میزبان بسته می‌شود.</li><li>Redroid privileged است و VM امنیتی محسوب نمی‌شود.</li><li>Basic Auth فعلی مشترک است و مجوز جداگانهٔ per-device ارائه نمی‌دهد.</li><li>این UI نمونه است؛ CLI و Compose عملیاتی‌اند و API چندکاربره هنوز در مرحلهٔ طراحی است.</li></ul><div className="tags"><span>React + TypeScript</span><span>Python Agent</span><span>Docker Compose</span></div></section></div></>}

        {page === 'settings' && <div className="settings-layout"><section className="panel"><div className="section-header"><h2>سیاست‌های فارم</h2><span className="tag">مدیریت خودکار</span></div><Setting title="ظرفیت همزمان" note="از CPU، RAM، cgroup و فشار لحظه‌ای محاسبه می‌شود؛ سقف مدیریتی فقط می‌تواند آن را کمتر کند." value={`${fa(state.capacity)} دستگاه`} /><Setting title="ظرفیت دستگاه‌های پایدار" note="از فضای واقعی /data و بودجهٔ هر دستگاه محاسبه می‌شود." value={`${fa(hostReport.catalog_capacity ?? 0)} دستگاه دیگر`} /><Setting title="خاموش‌شدن پس از پایان جلسه" note="داده حفظ می‌شود و پراکسی و صفحه نیز خاموش می‌شوند." value="فعال" /><Setting title="راه‌اندازی پس از ریبوت" note="روشن‌شدن فقط با درخواست اپراتور انجام می‌شود." value="غیرفعال" /><Setting title="نگهداری بکاپ" note="سیاست نگهداری و مقصد off-site از پنل عملیات تعیین می‌شود." value="نیازمند اتصال backend" /><Setting title="دسترسی تیم" note="OIDC، MFA و مجوز سطح دستگاه در نسخهٔ چندکاربره." value="طراحی‌شده" /></section><section className="panel settings-side"><h2>ترجیحات این نمایش</h2><label className="toggle-row"><span>نمای فشردهٔ دستگاه‌ها</span><input type="checkbox" checked={compact} onChange={e => setCompact(e.target.checked)} /></label><p>جزئیات زیرساخت، Compose و Coolify توسط نصب‌کننده مدیریت می‌شوند و در این صفحه قرار نمی‌گیرند.</p><hr /><h3>شروع دوبارهٔ نمونه</h3><p>تغییرات آزمایشی، دستگاه‌های افزوده‌شده و رویدادهای این جلسه پاک می‌شوند.</p><button className="secondary" onClick={() => { dispatch({ type: 'reset' }); setToast('محیط نمونه به وضعیت اولیه برگشت'); }}><RotateCcw size={16} />بازنشانی محیط نمونه</button></section></div>}
      </main><footer className="app-footer"><span>ANDROID FARM <b>CONSOLE</b></span><span>طراحی محصول · نسخهٔ ۰٫۱</span><span><LockKeyhole size={12} />داده‌های نمونه</span></footer>
    </div>

    {chosen && <Modal title={`دستگاه ${chosen.id}`} wide onClose={() => setSelected(null)}><div className="detail-heading"><div className={`device-symbol ${chosen.status}`}><Smartphone size={27} /></div><div><h3>{chosen.label}</h3><p dir="ltr">{maskPhone(chosen.phone)}</p></div><Status status={chosen.status} /></div><div className="detail-tabs">{[['overview', 'نمای کلی'], ['screen', 'کنترل صفحه'], ['events', 'رویدادهای دستگاه']].map(([id, text]) => <button key={id} className={detailTab === id ? 'selected' : ''} onClick={() => setDetailTab(id)}>{text}</button>)}</div>
      {detailTab === 'overview' && <div className="detail-body"><div className="detail-metrics"><div><Cpu size={19} /><span>مصرف CPU نمونه</span><b>{chosen.status === 'running' ? fa(chosen.cpu) : '۰'}٪</b></div><div><HardDrive size={19} /><span>حافظهٔ نمونه</span><b>{chosen.status === 'running' ? fa(chosen.ram) : '۰'} <small>GB</small></b></div><div><Globe2 size={19} /><span>تأخیر پراکسی</span><b>{chosen.proxyHealthy ? fa(chosen.latency) : '—'} <small>ms</small></b></div></div><dl className="detail-list"><div><dt>مسیر خروجی</dt><dd>{chosen.region} / SOCKS5 Sticky <span className={chosen.proxyHealthy ? 'green-text' : 'orange-text'}>{chosen.proxyHealthy ? 'سالم' : 'نیاز به بررسی'}</span></dd></div><div><dt>آخرین پشتیبان</dt><dd>{chosen.backup ?? 'هنوز ثبت نشده'}</dd></div><div><dt>هویت پایدار</dt><dd dir="ltr" className="mono">farm-{chosen.id}</dd></div><div><dt>حجم دادهٔ مستقل</dt><dd dir="ltr" className="mono">redroid-data-{chosen.id}</dd></div></dl><div className="notice compact-notice"><ShieldCheck size={18} /><p>توقف دستگاه داده‌ها را حذف نمی‌کند. هیچ عملیاتی در این نسخه روی سرور اجرا نمی‌شود.</p></div></div>}
      {detailTab === 'screen' && <div className="screen-preview"><div className="phone-frame"><div className="phone-camera" /><div className="phone-content"><Smartphone size={48} strokeWidth={1} /><b dir="ltr">{chosen.id}</b><span>{chosen.status === 'running' ? 'آماده در شبیه‌ساز' : 'دستگاه روشن نیست'}</span><div className="phone-home" /></div></div><div><span className="tag">پیش‌نمایش رابط کنترل</span><h3>جلسهٔ امن مرورگر</h3><p>در استقرار واقعی، کنترل زندهٔ scrcpy از route مستقیم زیر و با Basic Auth مشترک فارم باز می‌شود.</p><code dir="ltr">/d/{chosen.id}/</code><div className="notice compact-notice"><LockKeyhole size={17} /><p>این کنسول نمایشی تصویر زنده دریافت نمی‌کند.</p></div><button disabled className="secondary"><ExternalLink size={16} />اتصال زنده موجود نیست</button></div></div>}
      {detailTab === 'events' && <div className="detail-body">{state.events.filter(e => e.device === chosen.id).length ? state.events.filter(e => e.device === chosen.id).map(e => <div className="event" key={e.id}><Clock3 size={18} /><div><strong>{e.text}</strong><p>{time(e.at)}</p></div></div>) : <Empty title="رویدادی ثبت نشده" text="عملیات آزمایشی بعدی این دستگاه اینجا نمایش داده می‌شود." />}</div>}
      <div className="modal-footer"><button className="secondary" onClick={() => dispatch({ type: 'proxy', id: chosen.id })}><RotateCcw size={16} />تست پراکسی نمونه</button><button className="secondary" disabled={chosen.status !== 'off'} onClick={() => dispatch({ type: 'backup', id: chosen.id })}><Database size={16} />بکاپ نمونه</button><span className="spacer" />{['running', 'booting'].includes(chosen.status) ? <button className="danger" onClick={() => setConfirm(chosen)}><Power size={16} />پایان جلسه</button> : <button className="primary" disabled={!['off', 'error', 'queued'].includes(chosen.status)} onClick={() => quickAction(chosen)}><Play size={15} />{chosen.status === 'queued' ? 'لغو درخواست' : 'روشن کردن'}</button>}</div>
    </Modal>}

    {addOpen && <Modal title="افزودن دستگاه" onClose={() => setAddOpen(false)}><form className="device-form" onSubmit={addDevice}><div className="form-info"><span className="round-icon"><Smartphone size={23} /></span><div><strong dir="ltr">num{String(state.devices.length + 1).padStart(2, '0')}</strong><p>هویت و فضای ذخیره‌سازی مستقل</p></div></div><label>نام دستگاه<input autoFocus value={jobLabel} onChange={e => setJobLabel(e.target.value)} placeholder="مثلاً رجیستری تیم دوم" maxLength={50} required /></label><label>شمارهٔ آزمایشی<input value={jobPhone} onChange={e => setJobPhone(e.target.value)} placeholder="+989000009999" dir="ltr" inputMode="tel" autoComplete="off" required /></label><p className="field-hint">این محیط طراحی است؛ شماره یا اطلاعات واقعی وارد نکنید.</p><div className="notice compact-notice"><LockKeyhole size={17} /><p>در محصول نهایی، شماره به یک دستگاه یکتا و پراکسی اختصاصی متصل می‌شود.</p></div>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={() => setAddOpen(false)}>انصراف</button><button className="primary" type="submit"><Plus size={16} />افزودن دستگاه نمونه</button></div></form></Modal>}
    {proxyOpen && <Modal title="افزودن پراکسی" onClose={() => setProxyOpen(false)}><form className="device-form" onSubmit={addProxy}><div className="form-info"><span className="round-icon"><Network size={23} /></span><div><strong>اتصال اختصاصی و ثابت</strong><p>HTTP CONNECT یا SOCKS5 احراز هویت‌شده</p></div></div><label>عنوان اتصال<input autoFocus value={proxyLabel} onChange={e => setProxyLabel(e.target.value)} placeholder="مثلاً Frankfurt ISP 01" maxLength={80} required /></label><label>نوع<select value={proxyType} onChange={e => setProxyType(e.target.value as 'SOCKS5' | 'HTTP')}><option>SOCKS5</option><option>HTTP</option></select></label><label>کشور / منطقه<input value={proxyRegion} onChange={e => setProxyRegion(e.target.value)} maxLength={50} required /></label><p className="field-hint">در نسخهٔ متصل، endpoint، username، password و IP مورد انتظار از طریق فرم write-only و backend امن ثبت می‌شوند.</p><div className="notice compact-notice"><LockKeyhole size={17} /><p>رمز در جدول، log یا ENV نمایش داده نمی‌شود.</p></div><div className="form-actions"><button type="button" className="secondary" onClick={() => setProxyOpen(false)}>انصراف</button><button className="primary" type="submit"><Plus size={16} />افزودن نمونه</button></div></form></Modal>}
    {confirm && <Modal title="پایان جلسهٔ دستگاه" onClose={() => setConfirm(null)}><div className="confirm-body"><div className="confirm-icon"><Power size={28} /></div><h3>جلسهٔ <b dir="ltr">{confirm.id}</b> پایان یابد؟</h3><p>کنترل صفحه بسته می‌شود و دستگاه خاموش خواهد شد. تمام داده‌های دستگاه حفظ می‌شوند.</p><div className="form-actions"><button className="secondary" onClick={() => setConfirm(null)}>ادامهٔ جلسه</button><button className="danger" onClick={() => { dispatch({ type: 'stop', id: confirm.id }); setConfirm(null); }}>پایان جلسه</button></div></div></Modal>}
    {backupInfo && <Modal title={`پشتیبان ${backupInfo}`} onClose={() => setBackupInfo(null)}><div className="detail-body"><Database size={36} className="green-text" /><h3>رکورد نمایشی پشتیبان</h3><p>این رکورد برای بررسی تجربهٔ کاربری ساخته شده و آرشیو قابل دانلود ندارد. در نسخهٔ متصل، تأیید checksum، محل نگهداری و بازیابی به volume جدید در این بخش ارائه می‌شود.</p><div className="notice compact-notice"><ShieldCheck size={18} /><p>بازیابی نیازمند نقش مدیر و تأیید خاموش‌بودن دستگاه خواهد بود.</p></div></div></Modal>}
    {help && <Modal title="راهنمای شروع جلسه" onClose={() => setHelp(false)}><div className="detail-body"><ol className="help-steps"><li><b>دستگاه را انتخاب کنید</b><p>شماره، وضعیت پراکسی و آخرین پشتیبان را بررسی کنید.</p></li><li><b>جلسه را شروع کنید</b><p>یک جایگاه رزرو می‌شود؛ در ظرفیت کامل درخواست به صف می‌رود.</p></li><li><b>کنترل صفحه را باز کنید</b><p>در نسخهٔ متصل، پس از آماده‌شدن ADB صفحه قابل کنترل است.</p></li><li><b>جلسه را پایان دهید</b><p>داده‌ها حفظ می‌شوند و جایگاه برای دستگاه بعدی آزاد می‌شود.</p></li></ol><div className="notice compact-notice"><BookOpen size={18} /><p>Runbook کامل و دستورات واقعی میزبان در README مخزن هستند.</p></div></div></Modal>}
    {toast && <div className="toast" role="status"><Check size={18} /><span>{toast}</span><button aria-label="بستن پیام" onClick={() => setToast('')}><X size={16} /></button></div>}
  </div>;
}

function SearchField({ query, onChange }: { query: string; onChange: (value: string) => void }) { return <div className="search-field"><Search size={17} /><input aria-label="جست‌وجو" value={query} onChange={e => onChange(e.target.value)} placeholder="جست‌وجوی دستگاه، شماره یا موقعیت…" />{query && <button aria-label="پاک کردن جست‌وجو" onClick={() => onChange('')}><X size={14} /></button>}</div>; }
function Stat({ icon, label, value, suffix, note, spark }: { icon: ReactNode; label: string; value: string; suffix?: string; note: string; spark: string }) { return <div className={`stat-card ${spark}`}><div className="stat-top"><span>{label}</span>{icon}</div><div className="stat-number">{value}<small dir="ltr">{suffix}</small><svg viewBox="0 0 80 28" aria-hidden="true"><path d={spark === 'orange' ? 'M1 22 L14 22 L23 20 L34 20 L44 10 L54 10 L65 13 L78 7' : 'M1 24 L12 21 L22 24 L31 15 L41 17 L51 8 L63 11 L78 2'} /></svg></div><p><i />{note}</p></div>; }
function Empty({ title, text, action }: { title: string; text: string; action?: () => void }) { return <div className="empty"><div><Box size={29} strokeWidth={1.4} /></div><h3>{title}</h3><p>{text}</p>{action && <button className="secondary" onClick={action}>نمایش همهٔ دستگاه‌ها</button>}</div>; }
function Setting({ title, note, value }: { title: string; note: string; value: string }) { return <div className="setting-row"><div><h3>{title}</h3><p>{note}</p></div><span className="tag">{value}</span></div>; }
